package com.tejesh.spendwise.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF74F8E5)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A635F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE8E2)
val LightOnSecondaryContainer = Color(0xFF05201C)
val LightTertiary = Color(0xFF426277)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer =
    Color(0xFFC7E7FF)
val LightOnTertiaryContainer = Color(0xFF001E2D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFAFDFA)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFA)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDAE5E2)
val LightOnSurfaceVariant = Color(0xFF3F4947)
val LightOutline = Color(0xFF6F7977)

// Dark Theme Colors
val DarkPrimary = Color(0xFF53DBC9)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF005048)
val DarkOnPrimaryContainer = Color(0xFF74F8E5)
val DarkSecondary = Color(0xFFB1CCC6)
val DarkOnSecondary = Color(0xFF1C3531)
val DarkSecondaryContainer = Color(0xFF334B47)
val DarkOnSecondaryContainer = Color(0xFFCDE8E2)
val DarkTertiary = Color(0xFFAACBE1)
val DarkOnTertiary = Color(0xFF113346)
val DarkTertiaryContainer = Color(0xFF2A4A5E)
val DarkOnTertiaryContainer = Color(0xFFC7E7FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE1E3E1)
val DarkSurface = Color(0xFF191C1B)
val DarkOnSurface = Color(0xFFE1E3E1)
val DarkSurfaceVariant = Color(0xFF3F4947)
val DarkOnSurfaceVariant = Color(0xFFBEC9C6)
val DarkOutline = Color(0xFF899390)
