name: Android CI/CD for SpendWise

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_android:
    name: Build & Test Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./SpendWise

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./SpendWise

    - name: Run unit tests
      run: ./gradlew test
      working-directory: ./SpendWise

  build_and_push_functions_image:
    name: Build & Push Functions Docker Image
    needs: build_and_test_android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./spendwise-functions
        push: true
        tags: ghcr.io/${{ github.repository }}/spendwise-functions:latest

